Hurricane Irene Edited
mandli/surge-examples pull request #27
Opened 2021-01-20 16:48 UTC by suhsha21

2021-01-25 00:35 UTC, mandli requested changes
Most we just need to adjust paths.

2021-01-25 00:35 UTC, mandli commented on irene/setrun.py
> +    topo_path = os.path.join(datadir, 'IreneTopo2.nc')
Should remove the code that converts the NetCDF file

2021-01-25 00:35 UTC, mandli commented on irene/setrun.py
> +scratch_dir = os.path.join(os.environ["CLAW"], 'geoclaw', 'scratch')
Should not use the scratch directory for apps

2021-01-25 00:35 UTC, mandli commented on irene/setrun.py
> +    topo_data.topofiles.append([3, 1, 5, rundata.clawdata.t0,
This needs to be updated also for clawpack 5.8.0.

2021-01-25 00:35 UTC, mandli commented on irene/setrun.py
> +    atcf_path = os.path.join(scratch_dir, "bal092011.dat")
Also probably should keep this to the local directory rather than the scratch.

2021-01-27 21:15 UTC, suhsha21 commented
I fixed the paths and made the suggested changes. Thank you.

2021-02-03 15:57 UTC, merged